### ISSUE TITLE
textswap fails with -r 10

### ISSUE THREAD

**Issue by sbates130272** [sbates130272/capi-textswap#2]
sudo drop_caches && sudo ./build/textswap -R -E 50 demo.GoPower8.50.8G.dat -r 10 -c 8M -q 22
Starting Read Threads: Invalid argument

Other values of -r seem to work OK?

**Comment by lsgunth** [comment]
Fixed in 21ff9c8ca7ac39afd4f5f33c08cc865773d7dae0
